"use client";
import type { MDXComponents } from "mdx/types";

import * as RadixIcons from "@radix-ui/react-icons";

// Define your custom MDX components.
// const mdxComponents: MDXComponents = {
//   // Override the default <a> element to use the next/link component.
//   a: ({ href, children }) => <Link href={href as string}>{children}</Link>,
//   // Add a custom component.
//   MyComponent: () => <div>Hello World!</div>,
// };
import {
  ColorPalette,
  ColorCardList,
  PaletteGrid,
  TypographyScale,
  ComponentPreview,
  SpacingDemo,
} from "@foundry/ui/demos";

import {
  Button,
  CodeBlock,
  Avatar,
  Input,
  AvatarImage,
  Tooltip,
  AvatarFallback,
  Label,
  Switch,
  Slider,
  Badge,
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
  Checkbox,
  Dialog,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogFooter,
  DialogTitle,
  DialogDescription,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
  Flex,
  Heading,
  KBD,
  Message,
  Note,
  Popover,
  PopoverTrigger,
  PopoverContent,
  PopoverTitle,
  RadioGroup,
  RadioGroupItem,
  Scroller,
  Select,
  SelectItem,
  Separator,
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  Textarea,
  ToastDemo,
  ToastAction,
  ToastWithActionDemo,
  Toolbar,
  ToolbarButton,
  ToolbarSeparator,
  ToolbarToggleGroup,
  // RadixIcons,
  ToolbarToggleItem,
} from "@foundry/ui/components";

export const mdxComponents: MDXComponents = {
  pre: CodeBlock,
  Button,
  ColorPalette,
  ColorCardList,
  PaletteGrid,
  TypographyScale,
  ComponentPreview,
  Avatar,
  Input,
  AvatarImage,
  Tooltip,
  AvatarFallback,
  Label,
  Switch,
  Slider,
  Badge,
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
  Checkbox,
  Dialog,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogFooter,
  DialogTitle,
  DialogDescription,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
  Flex,
  Heading,
  KBD,
  Message,
  Note,
  Popover,
  PopoverTrigger,
  PopoverContent,
  PopoverTitle,
  RadioGroup,
  RadioGroupItem,
  Scroller,
  Select,
  SelectItem,
  Separator,
  SpacingDemo,
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  Textarea,
  ToastDemo,
  ToastAction,
  ToastWithActionDemo,
  Toolbar,
  ToolbarButton,
  ToolbarSeparator,
  ToolbarToggleGroup,
  RadixIcons,
  ToolbarToggleItem,
};
