import "./globals.css";
import "@foundry/ui/styles.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SiteLayout } from "./site-layout";
import { Client } from "./client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "// Foundry",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Client>
          <SiteLayout>{children}</SiteLayout>
        </Client>
      </body>
    </html>
  );
}
